TemplateApp/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TemplateApp.Models
{
    public class Product
    {
        public int ProductId { get; set; }

        public string ProductName { get; set; }

        public string ProductType { get; set; }

        public decimal ProductPrice { get; set; }

        public string ProductDescription { get; set; }

        public int Quantity { get; set; }
        public bool IsOrdered { get; set; }
        public string ProductImage { get; set; }
    }
}

TemplateApp/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using TemplateApp.Data;

namespace TemplateApp.Models
{
    public class ShoppingCart
    {
        private readonly TemplateContext _appDbContext;
        private ShoppingCart(TemplateContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public string ShoppingCartId { get; set; }

        public List<ShoppingCartItem> ShoppingCartItems { get; set; }

        public static ShoppingCart GetCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?
                .HttpContext.Session;

            var context = services.GetService<TemplateContext>();
            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

            session.SetString("CartId", cartId);

            return new ShoppingCart(context) { ShoppingCartId = cartId }; 
        }

        public void  AddToCart(Product item, int amount)
        {
            var shoppingCartItem =
                    _appDbContext.ShoppingCartItems.SingleOrDefault(
                        s => s.Product.ProductId == item.ProductId && s.ShoppingCartId == ShoppingCartId);

            if (shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem
                {
                    ShoppingCartId = ShoppingCartId,
                    Product = item,
                    Quantity = 1
                };
               // _appDbContext.ShoppingCart.Add(ShoppingCartId);
                _appDbContext.ShoppingCartItems.Add(shoppingCartItem);
            }
            else
            {
                shoppingCartItem.Quantity++;
            }
            _appDbContext.SaveChanges();
        }

        public int RemoveFromCart(Product product)
        {
            var shoppingCartItem =
                    _appDbContext.ShoppingCartItems.SingleOrDefault(
                        s => s.Product.ProductId == product.ProductId && s.ShoppingCartId == ShoppingCartId);

            var localAmount = 0;

            if (shoppingCartItem != null)
            {
                if (shoppingCartItem.Quantity > 1)
                {
                    shoppingCartItem.Quantity--;
                    localAmount = shoppingCartItem.Quantity;
                }
                else
                {
                    _appDbContext.ShoppingCartItems.Remove(shoppingCartItem);
                }
            }

            _appDbContext.SaveChanges();

            return localAmount;
        }

        public List<ShoppingCartItem> GetShoppingCartItems()
        {
            return ShoppingCartItems ??
                   (ShoppingCartItems =
                       _appDbContext.ShoppingCartItems.Where(c => c.ShoppingCartId == ShoppingCartId)
                           .Include(s => s.Product)
                           .ToList());
        }

        public void ClearCart()
        {
            var cartItems = _appDbContext
                .ShoppingCartItems
                .Where(cart => cart.ShoppingCartId == ShoppingCartId);

            _appDbContext.ShoppingCartItems.RemoveRange(cartItems);

            _appDbContext.SaveChanges();
        }

        
        public decimal GetShoppingCartTotal()
        {
            var total = _appDbContext.ShoppingCartItems.Where(c => c.ShoppingCartId == ShoppingCartId)
                .Select(c => c.Product.ProductPrice * c.Quantity).Sum();
            return total;
        }

        public Order CreateOrder()
        {
            // Flat rate shipping
            int shipping = 500;

            // Flat rate tax 10%
            var taxRate = 0.1M;

            var subtotal = _appDbContext.ShoppingCartItems.Sum(x => x.Product.ProductPrice * x.Quantity);
            var tax = Convert.ToInt32((subtotal + shipping) * taxRate);
            var total = subtotal + shipping + tax;

            var Order = new Order()
            {
                OrderDate = DateTime.UtcNow,
                Subtotal = subtotal,
                Shipping = shipping,
                Tax = tax,
                Total = total,
                OrderItems = _appDbContext.ShoppingCartItems.Select(x => new OrderItem()
                {
                    Product = x.Product,
                    Quantity = x.Quantity
                }).ToList()
            };

            _appDbContext.Orders.Add(Order);
            _appDbContext.SaveChanges();
            return Order;
        }
    }
}

TemplateApp/ViewModels/ShoppingCartViewModel.cs
using TemplateApp.Models;

namespace TemplateApp.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

TemplateApp/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TemplateApp.Data;
using TemplateApp.Models;

namespace TemplateApp.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }
        private readonly TemplateApp.Data.TemplateContext _context;

        public AboutModel(TemplateContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

TemplateApp/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TemplateApp.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

TemplateApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TemplateApp.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TemplateApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TemplateApp.Data;
using TemplateApp.Models;

namespace TemplateApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly TemplateApp.Data.TemplateContext _context;

        public IndexModel(TemplateApp.Data.TemplateContext context)
        {
            _context = context;
        }

        public IList<Product> Product { get;set; }

        public async Task OnGetAsync()
        {
            //Product = await _context.Product
          //      .Include(p => p.Employees).ToListAsync();
        }
    }
}

TemplateApp/Pages/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TemplateApp.Data;
using TemplateApp.Models;

namespace TemplateApp.Pages
{
    public class ProductsModel : PageModel
    {
        private readonly TemplateContext _context;


        public ProductsModel(TemplateContext context)
        {
            _context = context;
        }

        [BindProperty]
        public IList<Product> Products { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Products = await _context.Products.ToListAsync();
         
            return Page();
        }

        /*   public async Task<IActionResult> OnPostAsync()
            {
             /*   if (!ModelState.IsValid)
                {
                    return Page();
                }

                _context.Products.Add(Product);
                await _context.SaveChangesAsync();

                return RedirectToPage("./Index");
            }*/
    }
}

TemplateApp/Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Rewrite.Internal.ApacheModRewrite;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using PayPal.Api;
using SQLitePCL;
using TemplateApp.Data;
using TemplateApp.Models;
using TemplateApp.ViewModels;

namespace TemplateApp.Pages
{
    public class ShoppingCartModel : PageModel
    {
        public string configclientmode { get; }
        public string Message { get; set; }
        public string configclientid { get; }
        public string configclientsecret { get; }
        public ShoppingCartViewModel CurrentShoppingCart { get; set; }
        private readonly TemplateContext _context;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartModel(TemplateContext context, ShoppingCart shoppingCart,IConfiguration configuration)
        {
            _context = context;
            _shoppingCart = shoppingCart;
            configclientmode= configuration["Paypal:mode"];
            configclientid = configuration["Paypal:ClientId"];
            configclientsecret = configuration["Paypal:ClientSecret"];
        }

        public void OnGet()
        {
            Message = "Your application description page.";
        }

        public async Task<IActionResult> OnPostAddToShoppingCartAsync(int productId)
        {
            var selectedProduct = _context.Products.FirstOrDefault(p => p.ProductId == productId);

            if (selectedProduct != null)
            {
                _shoppingCart.AddToCart(selectedProduct, 1);
            }

            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            this.CurrentShoppingCart = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return Page();
        }

        
        private APIContext GetApiContext()
        {
            // Authenticate with PayPal
           
           var accessToken = new OAuthTokenCredential(configclientid,configclientsecret).GetAccessToken();
           // var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);

            return apiContext;
        }

        public async Task<IActionResult> OnPostCheckoutAsync()
        {
            /*  var shoppingCartItems = _shoppingCart.GetShoppingCartItems();
            if (shoppingCartItems.Any())
             {
                 // Create an Order object to store info about the shopping cart
                 var order =  _shoppingCart.CreateOrder();
                 // Get PayPal API Context using configuration from web.config
             //   var apiContext = GetApiContext();

                 // Create a new payment object
                 var payment = new Payment
                 {
                     intent = "sale",
                     payer = new Payer
                     {
                         payment_method = "paypal"
                     },
                     transactions = new List<Transaction>
                     {
                         new Transaction
                         {
                             description = $"BeerPal Brewery Shopping Cart Purchase",
                             amount = new Amount
                             {
                                 currency = "USD",
                                 total = (order.Total/100M).ToString(), // PayPal expects string amounts, eg. "20.00",
                                 details = new Details()
                                 {
                                     subtotal = (order.Subtotal/100M).ToString(),
                                     shipping = (order.Shipping/100M).ToString(),
                                     tax = (order.Tax/100M).ToString()
                                 }
                             },
                             item_list = new ItemList()
                             {
                                 items =
                                     order.OrderItems.Select(x => new Item()
                                     {
                                         description = x.Product.ProductName,
                                         currency = "USD",
                                         quantity = x.Quantity.ToString(),
                                         price = (x.Product.ProductPrice/100M).ToString(), // PayPal expects string amounts, eg. "20.00"
                                     }).ToList()
                             }
                         }
                     },
                     redirect_urls = new RedirectUrls
                     {
                         return_url = Url.Action("Return", "ShoppingCart"),
                         cancel_url = Url.Action("Cancel", "ShoppingCart")
                     }
                 };


                            // Send the payment to PayPal
                              var createdPayment = payment.Create(apiContext);

                              // Save a reference to the paypal payment
                              order.PayPalReference = createdPayment.id;
                              _context.SaveChanges();

                              // Find the Approval URL to send our user to
                              var approvalUrl =
                                  createdPayment.links.FirstOrDefault(
                                      x => x.rel.Equals("approval_url", StringComparison.OrdinalIgnoreCase));

                    // Send the user to PayPal to approve the payment
                    return Redirect(approvalUrl.href);
                }

             //   return RedirectToAction("Cart");
                return Page();*/
            return RedirectToPage("Thankyou");
        }

        public ActionResult OnPostReturn(string payerId, string paymentId)
        {
            // Fetch the existing order
            var order = _context.Orders.FirstOrDefault(x => x.PayPalReference == paymentId);

            // Get PayPal API Context using configuration from web.config
            var apiContext = GetApiContext();

            // Set the payer for the payment
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };

            // Identify the payment to execute
            var payment = new Payment()
            {
                id = paymentId
            };

            // Execute the Payment
            var executedPayment = payment.Execute(apiContext, paymentExecution);

        //    ClearCart();

            return RedirectToPage("Thankyou");
        }

        public ActionResult OnPostCancel()
        {
            // return View();
            return RedirectToPage("Thankyou");
        }
    }
    }

TemplateApp/Pages/ThankYou.cshtml.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Rewrite.Internal.ApacheModRewrite;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using PayPal.Api;
using SQLitePCL;
using TemplateApp.Data;
using TemplateApp.Models;
using TemplateApp.ViewModels;

namespace TemplateApp.Pages
{
    public class ThankYouModel : PageModel
    {

    }
}

TemplateApp/Pages/About.cshtml
@page
@using Microsoft.EntityFrameworkCore
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>Message</h3>

<p>Use this area to provide additional information.</p>

TemplateApp/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TemplateApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage Employees Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

TemplateApp/Pages/Products.cshtml
@page
@model TemplateApp.Pages.ProductsModel

@{
    ViewData["Title"] = "Products";
}

<h2>Select Your Favourite Cuisine from our kitchen and Enjoy some Finest Delicacies</h2>

<h4>Our Menu</h4>
<hr />

@foreach (var item in Model.Products)
{

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@item.ProductImage" alt="">
            <div class="caption">
                <h4 class="pull-right">@item.ProductPrice</h4>
                <h4>
                    <a>@item.ProductName</a>
                </h4>
                <p>@item.ProductPrice</p>
                <p>@item.ProductDescription</p>
                <p>@item.ProductId</p>

                <form method="Post" asp-page="./ShoppingCart" asp-page-handler="AddToShoppingCart" asp-route-productId=@item.ProductId>
                    <button>Add to Cart</button>
                    </form>
    
            </div>
        </div>
    </div>

}

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TemplateApp/Pages/ShoppingCart.cshtml
@page

@model ShoppingCartModel
@{
    ViewData["Title"] = "AboutShoppingCart";
}

<h2>Your shopping cart</h2>
<h4>Here is your order!</h4>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Selected amount</th>
        <th>Product</th>
        <th class="text-right">Price</th>
        <th class="text-right">Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model.CurrentShoppingCart.ShoppingCart.ShoppingCartItems)
    {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.ProductName</td>
            <td class="text-right">@line.Product.ProductPrice.ToString("c")</td>
            <td class="text-right">
                @((line.Quantity * line.Product.ProductPrice).ToString("c"))
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Total:</td>
        <td class="text-right">
            @Model.CurrentShoppingCart.ShoppingCartTotal.ToString("c")
        </td>
    </tr>
    </tfoot>
</table>

<custom:div progress-value="33">
</custom:div>

<div>
    <form method="Post" asp-page-handler="Checkout">
        <button>Checkout with PayPal</button>
    </form>

</div>

TemplateApp/Pages/ThankYou.cshtml
@page


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Thank You!!</h2>
            </div>
        </div>
    </div>


<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p>Your payment was successful. Your order is on its way!!</p>
            </div>
        </div>
    </div>
</div>

TemplateApp/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TemplateApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-page="/Index" class="navbar-brand">TemplateApp</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-page="/Index">Home</a></li>
                <li><a asp-page="/About">About</a></li>
                <li><a asp-page="/Contact">Contact</a></li>
                <li><a asp-page="/Employees/Index">Employees</a></li>
                <li><a asp-page="/Products">Menu</a></li>
            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
</nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TemplateApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>